spring:
  profiles:
    active: prod

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/final-quiz?serverTimezone=UTC
    username: root
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:dbtest
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
