spring:
  profiles:
    active: test

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/final-quiz?serverTimezone=UTC
    username: root
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:dbtest
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
